export default {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
    },
    {
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [
        { type: 'heroSection' },
        { type: 'csSection' },
        { type: 'aboutSection' },
        { type: 'capabilitiesSection' },
        { type: 'showcaseSection' },
        { type: 'talentSection' },
        { type: 'reasonsSection' },
        { type: 'reviewsSection' },
        { type: 'workSection' },
        { type: 'stepsSection' },
        { type: 'finalSection' },
        { type: 'faqSection' },
        { type: 'proofBarSection' },
      ],
    },
  ],
};
